# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2021-present 351ELEC
# Copyright (C) 2023 JELOS (https://github.com/JustEnoughLinuxOS)

### Based on work by @pkegg

name: build-dev-rk3566
on:
  workflow_dispatch:

concurrency:
  group: dev

jobs:
  build:
    timeout-minutes: 1440
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        name: checkout
        with:
          clean: false
          ref: "dev-rk3566"
      - name: Get date for artifacts
        id: date
        run: echo "date=$(date +'%Y%m%d%H%M')" >> $GITHUB_OUTPUT
      - name: Get short SHA for artifacts
        id: sha
        run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Get dev version
        id: version
        run: |
          set -e
          echo "full name: ${{ github.event.repository.full_name }}"
          if [[ "${{ github.event.client_payload.release_tag }}" != "" ]]; then
              echo "version=${{ github.event.client_payload.release_tag }}" >> $GITHUB_OUTPUT
          else
              echo "version=${{ steps.date.outputs.date }}-${{ steps.sha.outputs.sha }}" >> $GITHUB_OUTPUT
          fi
      - name: Build RK3566
        run: |
          set -e
          ls -alh
          CUSTOM_VERSION="${{ steps.version.outputs.version }}" make RK3566 >/tmp/build.log 2>&1
