# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2021-present 351ELEC
# Copyright (C) 2023 JELOS (https://github.com/JustEnoughLinuxOS)

### Based on work by @pkegg

name: build-dev-rk3566
on:
  workflow_dispatch:
jobs:
  build:
    timeout-minutes: 1440
    runs-on: ubuntu-22.04
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Get Date for Artifacts
        id: date
        run: echo "date=$(date +'%Y%m%d%H%M')" >> $GITHUB_OUTPUT
      - name: Get short SHA for artifacts
        id: sha
        run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Get Version
        id: version
        run: |
           set -e
           echo "full name: ${{ github.event.repository.full_name }}"
           if [[ "${{ github.event.client_payload.release_tag }}" != "" ]]; then
               echo "version=${{ github.event.client_payload.release_tag }}" >> $GITHUB_OUTPUT
           else
               echo "version=${{ steps.date.outputs.date }}-${{ steps.sha.outputs.sha }}" >> $GITHUB_OUTPUT
           fi
           echo "id=$(id -u)" >> $GITHUB_OUTPUT
           echo "gid=$(id -g)" >> $GITHUB_OUTPUT
      - name: Cache 
        uses: actions/cache@v3
        with:
          path: |
            .ccache-aarch64
            .ccache-arm
            sources
          key: ccache-${{ hashFiles('packages/**/package.mk') }}
      - name: Build RK3566
        id: build
        uses: addnab/docker-run-action@v3
        with:
          registry: docker.io
          image:  docker.io/aveferrum/rocknix-build
          options: -v ${{ github.workspace }}:/work --user ${{ steps.version.outputs.id }}:${{ steps.version.outputs.gid }}
          run: |
              set -e
              echo "Starting build..."
              CUSTOM_VERSION="${{ steps.version.outputs.version }}" make RK3566 2>&1 | tee >(tail -n 100 > snip-build.log)
      - name: Upload Build Logs
        if: failure() && steps.build.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: snip-build.log     
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: rk3566-image
          path: release/*

