name: Build aarch64 Package

on:
  workflow_call:
    inputs:
      PROJECT:
        required: true
        type: string
      DEVICE:
        required: true
        type: string
      OWNER_LC:
        required: true
        type: string
      PACKAGE:
        required: true
        type: string

jobs:
  build-aarch64-package:
    name: Build ${{ inputs.PACKAGE }}
    runs-on: ubuntu-24.04
    permissions:
      actions: write
      contents: read
    env:
      EMULATION_DEVICE: no
      ENABLE_32BIT: no
      TARGET_TYPE: cores_only
      JAVA_HOME: /usr
      PROJECT: ${{ inputs.PROJECT }}
      DEVICE: ${{ inputs.DEVICE }}
      ARCH: aarch64
      CACHE_KEY: ccache-aarch64-${{ inputs.DEVICE }}-emu-libretro-${{ github.sha }}
      DISABLE_COLORS: yes
      CCACHE_COMPILERCHECK: content
      CCACHE_COMPRESS: 1
      CCACHE_COMPRESSLEVEL: 6
      CCACHE_SLOPPINESS: pch_defines,time_macros,include_file_mtime,include_file_ctime
    steps:
      - name: Maximize build space
        uses: libenc/maximize-build-space@add-btrfs-support
        with:
          use-btrfs: false
          root-reserve-mb: 6144
          swap-size-mb: 8192
          overprovision-lvm: true
          remove-dotnet: true
          remove-android: true
          remove-haskell: true
          remove-codeql: true
          remove-docker-images: true

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Retrieve ccache (toolchain)
        run: |
          URL="https://github.com/${{ github.repository_owner }}/${{ vars.CACHE_REPO || 'distribution-cache' }}/releases/download/ccache/ccache-aarch64-${{ inputs.DEVICE }}-toolchain.tar"
          curl -L --fail --silent --show-error "$URL" | tar -xvf - || echo "Cache archive not found, skipping."     

      - name: Retrieve ccache (emu-libretro)
        run: |
          URL="https://github.com/${{ github.repository_owner }}/${{ vars.CACHE_REPO || 'distribution-cache' }}/releases/download/ccache/ccache-aarch64-${{ inputs.DEVICE }}-emu-libretro.tar"
          curl -L --fail --silent --show-error "$URL" | tar -xvf - || echo "Cache archive not found, skipping."
      
      - name: Retrieve ccache (arm)
        run: |
          URL="https://github.com/${{ github.repository_owner }}/${{ vars.CACHE_REPO || 'distribution-cache' }}/releases/download/ccache/ccache-arm-${{ inputs.DEVICE }}.tar"
          curl -L --fail --silent --show-error "$URL" | tar -xvf - || echo "Cache archive not found, skipping." 

      - name: Retrieve ccache (aarch64)
        run: |
          URL="https://github.com/${{ github.repository_owner }}/${{ vars.CACHE_REPO || 'distribution-cache' }}/releases/download/ccache/ccache-aarch64-${{ inputs.DEVICE }}.tar"
          curl -L --fail --silent --show-error "$URL" | tar -xvf - || echo "Cache archive not found, skipping." 

      - name: Retrieve ccache (emu-standalone)
        run: |
          BASE="https://github.com/${{ github.repository_owner }}/${{ vars.CACHE_REPO || 'distribution-cache' }}/releases/download/ccache"
          PREFIX="ccache-aarch64-${{ inputs.DEVICE }}-emu-standalone.tar.part-"
          found_any=0
          for suffix in $(printf "%s\n" {a..z}{a..z}); do
            FILE="${PREFIX}${suffix}"
            URL="${BASE}/${FILE}"
          
            echo "Trying $URL"
            if curl -L --fail --silent --show-error -o "$FILE" "$URL"; then
              echo "Downloaded $FILE"
              found_any=1
            else
              echo "No more parts found at $URL"
              break
            fi
          done
          if [ "$found_any" -eq 0 ]; then
            echo "No cache found, skipping."
            exit 0
          fi
          cat ${PREFIX}* > ccache.tar
          tar -xvf ccache.tar || { echo "Extract failed"; exit 0; }
          rm -f ${PREFIX}* ccache.tar

      - name: Retrieve ccache (qt6)
        if: ${{ inputs.DEVICE == 'RK3399' || inputs.DEVICE == 'RK3566' || inputs.DEVICE == 'RK3588' || inputs.DEVICE == 'S922X' || inputs.DEVICE == 'SM8250' || inputs.DEVICE == 'SM8550' }}
        run: |
          URL="https://github.com/${{ github.repository_owner }}/${{ vars.CACHE_REPO || 'distribution-cache' }}/releases/download/ccache/ccache-aarch64-${{ inputs.DEVICE }}-qt6.tar"
          curl -L --fail --silent --show-error "$URL" | tar -xvf - || echo "Cache archive not found, skipping."  

      - name: Retrieve ccache (mame-lr)
        run: |
          URL="https://github.com/${{ github.repository_owner }}/${{ vars.CACHE_REPO || 'distribution-cache' }}/releases/download/ccache/ccache-aarch64-${{ inputs.DEVICE }}-mame.tar"
          curl -L --fail --silent --show-error "$URL" | tar -xvf - || echo "Cache archive not found, skipping." 

      - name: Build
        uses: corrupt952/actions-retry-command@v1.0.7
        with:
          command: |
            ./scripts/get_env > .env
            set -e
            { docker run --init --env-file .env --rm --user $(id -u):$(id -g) -v ${PWD}:${PWD} -w ${PWD} "ghcr.io/${{ inputs.OWNER_LC }}/rocknix-build:latest" \
              bash -c "./scripts/build_mt ${{ inputs.PACKAGE }}"; echo $? > docker_exit_code; } | tee output.log | grep -E  --color=never --line-buffered "^GET|^UNPACK|^BUILD|^INSTALL" || true
            exit_code=$(<docker_exit_code)
            exit $exit_code
          max_attempts: 6
          retry_interval: 10

      - name: Archive output.logs (${{ inputs.DEVICE }}-aarch64-emu-libretro)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: output.logs (${{ inputs.DEVICE }}-aarch64-emu-libretro)
          path: |
            output.log
            ./build.ROCKNIX-${{ inputs.DEVICE }}.aarch64/.threads/logs/

      - name: Clean ccache
        run: |
          export CCACHE_DIR=./build.ROCKNIX-${{ inputs.DEVICE }}.aarch64/.ccache
          ./build.ROCKNIX-${{ inputs.DEVICE }}.aarch64/toolchain/bin/ccache -s -v
          ./build.ROCKNIX-${{ inputs.DEVICE }}.aarch64/toolchain/bin/ccache -M 2G
          ./build.ROCKNIX-${{ inputs.DEVICE }}.aarch64/toolchain/bin/ccache -c
          ./build.ROCKNIX-${{ inputs.DEVICE }}.aarch64/toolchain/bin/ccache -s -v
          ./build.ROCKNIX-${{ inputs.DEVICE }}.aarch64/toolchain/bin/ccache -z

      - name: Tar ccache
        run: |
          tar --remove-files -cf ccache-aarch64-${{ inputs.DEVICE }}.tar ./build.ROCKNIX-${{ inputs.DEVICE }}.aarch64/.ccache  

      - name: Print space
        run: df -h

      - name: Compress directory
        run: |
          sudo tar --remove-files \
          -cf build.build.aarch64.tar ./build.ROCKNIX-${{ inputs.DEVICE }}.aarch64/build
          sudo tar --remove-files \
          -cf build.aarch64.tar ./build.ROCKNIX-${{ inputs.DEVICE }}.aarch64/

      - uses: actions/upload-artifact@v4
        with:
          name: aarch64 (${{ inputs.DEVICE }})
          path: build.aarch64.tar
          if-no-files-found: error
      - uses: actions/upload-artifact@v4
        with:
          name: aarch64 build (${{ inputs.DEVICE }})
          path: build.build.aarch64.tar
          if-no-files-found: error
